packageName: 'sense-angular-directives'
buildDevDir: './dist'
buildReleaseDir: './dist'
taskChains:
  "build":
    - "clean:tmp"
    - "copy:toTmp"
    - "import:fromLocal"
    - "less:each"
    - "replace:tmp"
    - "jsonlint:tmp"
    - "htmlmin:tmp"
    - "clean:buildRelease"
    - "copy:tmpToRelease"
    - "clean:tmp"

