packageName: 'sense-angular-directives'
buildDevDir: './dist'
buildReleaseDir: './dist'
taskChains:
  "build":
    - "shell"
    - "clean:tmp"
    - "copy:toTmp"
    - "import:fromLocal"
    - "less:reduce"
    - "replace:tmp"
    - "clean:tmpIllegal"              #clean illegal files
    - "jsonlint:tmp"
    - "htmlmin:tmp"
    - "cleanCss:tmp"
    - "clean:buildDev"
    - "header-js:tmp"
    - "copy:tmpToDev"
    - "zip:dev"
    - "clean:localExtensionDir"
    - "deploy:toLocal"
    - "deploy:toSsh"
    - "deploy:viaShell"
    - "clean:tmp"

